# api configuration
api:
  id: "17997958"

# Listener Configuration
http:
  host: "0.0.0.0"
  port: "8081"
  basePath: "api/*"

# Salesforce Configuration  
sfdc:
  username: "beauty@caelius.com"
  password: "![OHj8W1F7adD8u4UD5FRUVRj+v2a5eIqp]"
  token: "![lu8IzoK006z3Zt/go3ekaTJPmTmCoyslqvunsFdmcJo=]"
  

  
